CREATE TABLE user(
  id INTEGER PRIMARY KEY, 
  username STRING NOT NULL, 
  hash STRING NOT NULL, 
  size INT NOT NULL, 
  isAdmin BOOLEAN NOT NULL, 
  UNIQUE(username)
);
CREATE TABLE token(
  id INTEGER PRIMARY KEY,
  hash STRING NOT NULL,
  app STRING NOT NULL,
  user INT NOT NULL,
  FOREIGN KEY(user) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE data(
  id INTEGER PRIMARY KEY, 
  app STRING NOT NULL, 
  fragment STRING NOT NULL, 
  value NOT NULL, 
  timestamp INT NOT NULL, 
  user INT NOT NULL, 
  public INTEGER NOT NULL,
  UNIQUE(app, user, fragment),  
  FOREIGN KEY(user) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE share(
  id INTEGER PRIMARY KEY, 
  user INT NOT NULL, 
  data INT NOT NULL, 
  FOREIGN KEY(user) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE, 
  FOREIGN KEY(data) REFERENCES data(id) ON DELETE CASCADE ON UPDATE CASCADE,
  UNIQUE(user, data)
);